#!/usr/bin/env bash

function check_link(){
    src=$1
    dest=$2
    if [[ -e "$dest" ]]; then
        echo "already exists: $dest"
    elif [[ ! -e "$src" ]]; then
        echo "not found: $src"
    else
        ln -vs "$src" "$dest"
    fi
}

function pwd_link(){
    check_link $PWD/$1 $2
}

function host_link(){
    check_link $PWD/$1-$(hostname) $PWD/$1
}


pwd_link zsh/zshrc ~/.zshrc

pwd_link vim/vimrc ~/.vimrc

pwd_link git/gitconfig ~/.gitconfig
pwd_link git/git-completion.bash ~/.git-completion.bash

host_link awesome/rc.lua
host_link awesome/conkyrc
pwd_link awesome ~/.config/awesome
pwd_link awesome/conkyrc ~/.conkyrc

pwd_link python/matplotlibrc ~/.matplotlib/
pwd_link python/ipython ~/.config/

host_link system/xinitrc
pwd_link system/xinitrc ~/.xinitrc
pwd_link system/xmodmaprc ~/.xmodmaprc
pwd_link system/Xresources ~/.Xresources

host_link system/xbindkeysrc
pwd_link system/xbindkeysrc ~/.xbindkeysrc

pwd_link uzbl ~/.config/uzbl

pwd_link shell/screenrc ~/.screenrc

pwd_link r/Renviron ~/.Renviron
pwd_link r/Rprofile ~/.Rprofile

if [[ -d "$HOME/.config/fontconfig" ]]; then
    # on arch
    pwd_link font/fonts.conf ~/.config/fontconfig/fonts.conf
else
    # on debian
    pwd_link font/fonts.conf ~/.fonts.conf
fi
