#!/usr/bin/env bash

function check_link(){
    src=$1
    dest=$2
    if [[ -e "$dest" ]]; then
        echo "already exists: $dest"
    elif [[ ! -e "$src" ]]; then
        echo "not found: $src"
    else
        ln -vs "$src" "$dest"
    fi
}

function pwd_link(){
    check_link $PWD/$1 $2
}

function host_link(){
    check_link $PWD/$1-$(hostname) $PWD/$1
}


pwd_link zsh/zshrc ~/.zshrc

pwd_link vim/vimrc ~/.vimrc

pwd_link git/gitconfig ~/.gitconfig
pwd_link git/global-gitignore ~/.global-gitignore
pwd_link git/git-completion.bash ~/.git-completion.bash

pwd_link awesome ~/.config/awesome
host_link awesome/conkyrc
pwd_link awesome/conkyrc ~/.conkyrc

pwd_link python/matplotlib ~/.config/matplotlib
pwd_link python/ipython ~/.config/ipython

host_link xorg/xinitrc
pwd_link xorg/xinitrc ~/.xinitrc
host_link xorg/xbindkeysrc
pwd_link xorg/xbindkeysrc ~/.xbindkeysrc
host_link xorg/xmodmaprc
pwd_link xorg/xmodmaprc ~/.xmodmaprc
pwd_link xorg/Xresources ~/.Xresources
pwd_link xorg/mimeapps.list ~/.local/share/applications/mimeapps.list

pwd_link uzbl ~/.config/uzbl

pwd_link zathura ~/.config/zathura

pwd_link shell/screenrc ~/.screenrc
pwd_link shell/bashrc ~/.bashrc
pwd_link shell/bash_profile ~/.bash_profile
pwd_link shell/bash_aliases ~/.bash_aliases
pwd_link shell/colordiffrc ~/.colordiffrc

pwd_link r/Renviron ~/.Renviron
pwd_link r/Rprofile ~/.Rprofile

pwd_link font/fonts.conf ~/.config/fontconfig/fonts.conf

pwd_link mpd/mpd.conf ~/.mpd/mpd.conf
