alias mps='makepkg -s'
alias mpsi='makepkg -si'
alias pac='sudo pacman -S'
alias pacc='sudo pacman -Sc'
alias pacf='pacman -Ql'
alias paci='pacman -Si'
alias pacli='pacman -Qi'
alias pacll='pacman -Qqm'
alias paclo='pacman -Qdt'
alias pacm='sudo pacman -U'
alias paco='pacman -Qo'
alias pacr='sudo pacman -Rs'
alias pacs='pacman -Ss'
alias pacu='sudo pacman -Syu'

alias net='sudo netctl start'
alias netd='sudo netctl stop-all'
alias netl='netctl list'
