# set by default in arch but not debian
if [[ -z "$XDG_CONFIG_HOME" ]]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi
if [[ -z "$XDG_DATA_HOME" ]]; then
    export XDG_DATA_HOME="$HOME/.local/share"
fi
if [[ -z "$XDG_CACHE_HOME" ]]; then
    export XDG_CACHE_HOME="$HOME/.cache"
fi

ETC=$XDG_CONFIG_HOME/etc
PETC=$XDG_CONFIG_HOME/petc  # private config
ZSH=$ETC/zsh
ZSH_THEME="mytheme-red"  # overridden by computer-specific setup

autoload -U compinit
compinit -i

source $ZSH/source-files

source $ZSH/themes/$ZSH_THEME.zsh-theme
