# much of this comes from oh-my-zsh

autoload -U compinit
compinit -i

ETC=/home/kyle/.config/etc
PETC=/home/kyle/.config/petc  # private config
ZSH=$ETC/zsh
ZSH_THEME="mytheme-red"  # overridden by computer-specific setup

source $ZSH/source-files
source $ZSH/themes/$ZSH_THEME.zsh-theme
